require "bundler/capistrano"

set :application, "bridge_city"
 
set :scm, :git
set :git_enable_submodules, 1
set :repository, "git@github.com:rclosner/bridge_city"
set :branch, "master"
set :ssh_options, { :forward_agent => true }
 
set :stage, :production
set :user, "deploy"
set :use_sudo, false
set :runner, "deploy"
set :deploy_to, "/var/www/ryan_closner"
set :app_server, :passenger
set :domain, "ryanclosner.com"
